-- MySQL Script generated by MySQL Workbench
-- Wed Mar 18 20:07:51 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`OwnerInformation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`OwnerInformation` ;

CREATE TABLE IF NOT EXISTS `mydb`.`OwnerInformation` (
  `OwnerID` INT NOT NULL AUTO_INCREMENT,
  `OwnerName` VARCHAR(45) NOT NULL,
  `ContactNumber` DECIMAL(10) NOT NULL,
  `NameOfPet` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`OwnerID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PetInformation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`PetInformation` ;

CREATE TABLE IF NOT EXISTS `mydb`.`PetInformation` (
  `PetID` INT NOT NULL AUTO_INCREMENT,
  `NameOfPet` VARCHAR(45) NOT NULL,
  `Breed` VARCHAR(45) NOT NULL,
  `Color_Markings` VARCHAR(45) NOT NULL,
  `Birthdate` DATE NOT NULL,
  `Gender` VARCHAR(1) NOT NULL,
  `Neutured_Spayedd` VARCHAR(1) NOT NULL,
  `BasicTrainingRegistered` VARCHAR(1) NOT NULL,
  `Walk_Train_PlayRegistererd` VARCHAR(1) NOT NULL,
  `OffLeashOperationRegistered` VARCHAR(1) NOT NULL,
  `OwnerSignature` VARCHAR(45) NOT NULL,
  `OwnerInformation_OwnerID` INT NULL,
  PRIMARY KEY (`PetID`),
  INDEX `fk_PetInformation_OwnerInformation1_idx` (`OwnerInformation_OwnerID` ASC) VISIBLE,
  CONSTRAINT `fk_PetInformation_OwnerInformation1`
    FOREIGN KEY (`OwnerInformation_OwnerID`)
    REFERENCES `mydb`.`OwnerInformation` (`OwnerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`HeartwormInformation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`HeartwormInformation` ;

CREATE TABLE IF NOT EXISTS `mydb`.`HeartwormInformation` (
  `PetID` INT NOT NULL,
  `HeartWormTest` VARCHAR(1) NULL,
  `HeartWormPreventionTreatment` VARCHAR(45) NULL,
  PRIMARY KEY (`PetID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`HealthHistory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`HealthHistory` ;

CREATE TABLE IF NOT EXISTS `mydb`.`HealthHistory` (
  `PetID` INT NOT NULL,
  `DHPP` DATE NOT NULL,
  `Lepto` DATE NOT NULL,
  `Bordetella` DATE NOT NULL,
  `Rabies` DATE NOT NULL,
  `Lyme` DATE NOT NULL,
  `Giardia` VARCHAR(45) NOT NULL,
  `FecalExam` DATE NOT NULL,
  `HeartwormTest` VARCHAR(45) NOT NULL,
  `OtherVacc` VARCHAR(45) NOT NULL,
  `TimeSpentOutside` DATE NOT NULL,
  `Diet` VARCHAR(45) NOT NULL,
  `HeartwormInformation_PetID` INT NULL,
  PRIMARY KEY (`PetID`),
  INDEX `fk_HealthHistory_PetInformation1_idx` (`PetID` ASC) VISIBLE,
  INDEX `fk_HealthHistory_HeartwormInformation1_idx` (`HeartwormInformation_PetID` ASC) VISIBLE,
  CONSTRAINT `fk_HealthHistory_PetInformation1`
    FOREIGN KEY (`PetID`)
    REFERENCES `mydb`.`PetInformation` (`PetID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_HealthHistory_HeartwormInformation1`
    FOREIGN KEY (`HeartwormInformation_PetID`)
    REFERENCES `mydb`.`HeartwormInformation` (`PetID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Events`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Events` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Events` (
  `RegistrationNumber` INT NOT NULL AUTO_INCREMENT,
  `PetID` INT NOT NULL,
  `RegisterDate` DATETIME NOT NULL,
  `EventName` VARCHAR(45) NOT NULL,
  `TrainerName` VARCHAR(45) NOT NULL,
  `PetInformation_PetID` INT NULL,
  PRIMARY KEY (`RegistrationNumber`, `PetID`),
  INDEX `fk_Events_PetInformation1_idx` (`PetInformation_PetID` ASC) VISIBLE,
  CONSTRAINT `fk_Events_PetInformation1`
    FOREIGN KEY (`PetInformation_PetID`)
    REFERENCES `mydb`.`PetInformation` (`PetID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
