-- MySQL Script generated by MySQL Workbench
-- Sat Mar 14 13:05:34 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`OwnerInformation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`OwnerInformation` ;

CREATE TABLE IF NOT EXISTS `mydb`.`OwnerInformation` (
  `OwnerID` INT NOT NULL AUTO_INCREMENT,
  `OwnerName` VARCHAR(45) NOT NULL,
  `ContactNumber` INT NOT NULL,
  `NameOfPet` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`OwnerID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`BasicTrainingCourse`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`BasicTrainingCourse` ;

CREATE TABLE IF NOT EXISTS `mydb`.`BasicTrainingCourse` (
  `PetID` INT NOT NULL,
  `RegisteredDates` VARCHAR(45) NULL,
  PRIMARY KEY (`PetID`))
ENGINE = InnoDB
MAX_ROWS = 10;


-- -----------------------------------------------------
-- Table `mydb`.`WTPTrainingCourse`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`WTPTrainingCourse` ;

CREATE TABLE IF NOT EXISTS `mydb`.`WTPTrainingCourse` (
  `PetID` INT NOT NULL,
  `RegisteredDates` VARCHAR(45) NULL,
  `PrivateRegisteredDates` VARCHAR(45) NULL,
  PRIMARY KEY (`PetID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`OLOTrainingCourse`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`OLOTrainingCourse` ;

CREATE TABLE IF NOT EXISTS `mydb`.`OLOTrainingCourse` (
  `PetID` INT NOT NULL,
  `RegisteredDates` VARCHAR(45) NULL,
  PRIMARY KEY (`PetID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PetInformation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`PetInformation` ;

CREATE TABLE IF NOT EXISTS `mydb`.`PetInformation` (
  `PetID` INT NOT NULL AUTO_INCREMENT,
  `OwnerInformation_OwnerID` INT NOT NULL,
  `NameOfPet` VARCHAR(45) NOT NULL,
  `Breed` VARCHAR(45) NOT NULL,
  `Color/Markings` VARCHAR(45) NOT NULL,
  `Age / Birthday` INT NOT NULL,
  `Gender` VARCHAR(1) NOT NULL,
  `Neutured / Spayedd` VARCHAR(1) NOT NULL,
  `BasicTrainingRegistered` VARCHAR(1) NOT NULL,
  `Walk-Train-PlayRegistererd` VARCHAR(1) NOT NULL,
  `OffLeashOperationRegistered` VARCHAR(1) NOT NULL,
  `BasicTrainingCourse_PetID` INT NULL,
  `WTPTrainingCourse_PetID` INT NULL,
  `OLOTrainingCourse_PetID` INT NULL,
  PRIMARY KEY (`PetID`, `OwnerInformation_OwnerID`),
  INDEX `fk_PetInformation_OwnerInformation_idx` (`OwnerInformation_OwnerID` ASC) VISIBLE,
  INDEX `fk_PetInformation_BasicTrainingCourse1_idx` (`BasicTrainingCourse_PetID` ASC) VISIBLE,
  INDEX `fk_PetInformation_WTPTrainingCourse1_idx` (`WTPTrainingCourse_PetID` ASC) VISIBLE,
  INDEX `fk_PetInformation_OLOTrainingCourse1_idx` (`OLOTrainingCourse_PetID` ASC) VISIBLE,
  CONSTRAINT `fk_PetInformation_OwnerInformation`
    FOREIGN KEY (`OwnerInformation_OwnerID`)
    REFERENCES `mydb`.`OwnerInformation` (`OwnerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PetInformation_BasicTrainingCourse1`
    FOREIGN KEY (`BasicTrainingCourse_PetID`)
    REFERENCES `mydb`.`BasicTrainingCourse` (`PetID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PetInformation_WTPTrainingCourse1`
    FOREIGN KEY (`WTPTrainingCourse_PetID`)
    REFERENCES `mydb`.`WTPTrainingCourse` (`PetID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PetInformation_OLOTrainingCourse1`
    FOREIGN KEY (`OLOTrainingCourse_PetID`)
    REFERENCES `mydb`.`OLOTrainingCourse` (`PetID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`HealthHistory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`HealthHistory` ;

CREATE TABLE IF NOT EXISTS `mydb`.`HealthHistory` (
  `PetInformation_PetID` INT NOT NULL,
  `DHPP` VARCHAR(1) NOT NULL,
  `Lepto` VARCHAR(1) NOT NULL,
  `Bordetella` VARCHAR(1) NOT NULL,
  `Rabies` VARCHAR(1) NOT NULL,
  `Lyme` VARCHAR(1) NOT NULL,
  `Giardia` VARCHAR(1) NOT NULL,
  `FecalExam` VARCHAR(1) NOT NULL,
  `HeartwormTest` VARCHAR(1) NOT NULL,
  `OtherVacc` VARCHAR(45) NOT NULL,
  `TimeSpentOutside` DECIMAL(4,2) NOT NULL,
  `Diet` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`PetInformation_PetID`),
  INDEX `fk_HealthHistory_PetInformation1_idx` (`PetInformation_PetID` ASC) VISIBLE,
  CONSTRAINT `fk_HealthHistory_PetInformation1`
    FOREIGN KEY (`PetInformation_PetID`)
    REFERENCES `mydb`.`PetInformation` (`PetID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`HeartwormInformation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`HeartwormInformation` ;

CREATE TABLE IF NOT EXISTS `mydb`.`HeartwormInformation` (
  `HealthHistory_PetInformation_PetID` INT NOT NULL,
  `HeartwormTest` VARCHAR(1) NOT NULL,
  `HeartwormPrevTreatment` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`HealthHistory_PetInformation_PetID`),
  CONSTRAINT `fk_HeartwormInformation_HealthHistory1`
    FOREIGN KEY (`HealthHistory_PetInformation_PetID`)
    REFERENCES `mydb`.`HealthHistory` (`PetInformation_PetID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
